version: 0.7.{build}
environment:
  nodejs_version: '6'
branches:
  only:
    - /master
    - /dev
build: off
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - ps: git config --global core.autocrlf true
before_build:
  - ps: Install-Product node $env:nodejs_version
  - ps: node --version
  - ps: npm --version
  - ps: npm install
test_script:
  - ps: 'npm run test # PowerShell' # Pass comment to PS for easier debugging
deploy: off
