version: 0.7.{build}
environment:
  nodejs_version: '6'
branches:
  only:
    - /master
    - /dev
build: off
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - ps: git config --global core.autocrlf true
before_build:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm isntall
test_script:
  - npm run test
deploy: off
